### ISSUE TITLE
The mingw32 environment is too old.

### ISSUE THREAD

**Issue by nicolasnoble** [rake-compiler/rake-compiler-dock#12]
So I finally managed to get what I needed to do go create @grpc ruby gems. However, I had to heavily modify the Dockerfile for rake-compiler-dock, and [commit it to the repository](https://github.com/grpc/grpc/blob/release-0_13/third_party/rake-compiler-dock/Dockerfile). I am not happy about that, and I would love if we could make it so that grpc builds out of the box using rake-compiler-dock. But the changes I've made are extremely grpc-centric, and won't work for you without adaptation. Here's the first big issue I've encountered.

The current Docker image for rake-compiler-dock is using `mingw32`. The problem with that package is it's pretty much [obsolete](http://packages.ubuntu.com/search?keywords=mingw32&searchon=names&suite=all&section=all), [superseded](http://packages.ubuntu.com/search?keywords=mingw-w64&searchon=names&suite=all&section=all) by `mingw-w64`. In fact, grpc can't be used with it. The main reason is that it's using antediluvian headers, from the Windows XP era, and doesn't have [features](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682052%28v=vs.85%29.aspx) that grpc [requires](https://github.com/grpc/grpc/blob/release-0_13/include/grpc/impl/codegen/sync_win32.h) from its public headers API. In other words, if you are trying to compile a piece of C code (the ruby extension in that case) against grpc targeting Windows, you can't do that if your Windows SDK is the old mingw32 environment - we require at least Windows Vista.

I don't know if you have any desire to migrate your environment to mingw-w64, but considering it's already disappearing from Ubuntu, it might be a good idea to upgrade at some point.

Here's a list of problems, issues and various thoughts I had while dealing with mingw-w64, if that can help you with the migration, should you decide to go for it.
- I am not sure what's special about the "_rubenvb" mingw-w64 compilers you're downloading, but maybe they're not so much necessary after that change ? I didn't try touching them, but my gut feeling would be to get rid of these after migrating 
- Ruby 1.8 and 1.9 didn't compile using it. I didn't really try poking these, as grpc's ruby implementation requires 2.0.0+ anyway. I just got rid of them. Sorry. Shall you need it, I can be of help if you get stuck on these, just contact me. So right now, grpc's rake-compiler-dock image only contains 2.0.0, 2.1.5, 2.2.2 and 2.3.0.
- Once installed, all versions of Ruby had a definition of `gettimeofday` in `win32.h` which collides with mingw's. I [pushed them away](https://github.com/grpc/grpc/blob/release-0_13/third_party/rake-compiler-dock/Dockerfile#L180).
- Once installed, Ruby 2.0.0-p645 has [a broken test](https://github.com/ruby/ruby/blob/ruby_2_0_0/include/ruby/win32.h#L781) to check for MINGW64, and enters a [control path](https://github.com/ruby/ruby/blob/ruby_2_0_0/include/ruby/win32.h#L798) which doesn't work on the new environment. I [pushed it away](https://github.com/grpc/grpc/blob/release-0_13/third_party/rake-compiler-dock/Dockerfile#L181).
- When linking, the mingw-w64 environment creates a direct dependency on libgcc-XXX.dll, and transitive dependencies to others. I solved that by [adding `-static`](https://github.com/grpc/grpc/blob/release-0_13/src/ruby/ext/grpc/extconf.rb#L100) on the link options of the grpc extension, which is obviously not really something you should force everyone to. But pushing away the flurry of dlls directly into the image might be a good alternative.
- Even when using `-static`, it still wanted a dependency on libwinpthread.dll. I [pushed it away](https://github.com/grpc/grpc/blob/release-0_13/third_party/rake-compiler-dock/Dockerfile#L182) by mangling the docker image directly. Which also shows what I was talking about in my previous point.
- When using `-static`, obviously, it's using the static version of the ruby runtime dll. In all cases, this is a big no-no, so [my workaround](https://github.com/grpc/grpc/blob/release-0_13/third_party/rake-compiler-dock/Dockerfile#L184) might still be useful in the general case when people would shoot themselves in the foot using `-static`.

That's about it for the mingw-w64 issue :)

**Comment by larskanis** [comment]
The ancient mingw32 package is used for ruby-1.8 and 1.9, only, because mingw-w64 isn't binary compatible in several ways. Some gems still support these versions, so that I'll keep it in, as long as it isn't in the way. Of course, many gems can not be compiled with mingw32, but these gems typically don't support these outdated ruby versions anyway and set `RUBY_CC_VERSION` accordingly.

Rake-compiler-dock's main target platform is the RubyInstaller and the RubyInstaller is more or less bound to [fixed gcc/mingw versions](http://rubyinstaller.org/downloads/) . Even the RubyInstaller version 2.3 [will use the old mingw-4.7.2 package](https://github.com/oneclick/rubyinstaller/issues/297) .

Using the mingw-w64 version 4.8.2 from the Ubuntu repository, results in all the issues you described above. I managed to build several gems that way, but it always required some specific tweaking. It's possible to tweak the build process of each and every gem, so that it works with a newer mingw version (>4.7), but most gem authors don't have the required knowledge or intention. That's why I'm still using the older rubenvb mingw versions - it's exactly the same version, that RubyInstaller versions 2.0 and above are compiled with. Extensions simply build and run without any further tweaking.

I mitigated some function stubs, that are missing in the rubenvb mingw gcc, with [workarounds like this](https://github.com/rails-sqlserver/tiny_tds/commit/7869312f93af573543cbcead57ce04831a41e3f2) , so far.

As long as RubyInstaller isn't upgraded and doesn't ship the required base DLLs (libgcc-XXX.dll, libwinpthread.dll, etc.), I don't think it's a good idea to switch to gcc >=4.8. Maybe building the cross ruby per `--enable-static` could be an alternative, but I didn't test that so far.

Did you try to build grpc with the downloaded rubenvb gcc versions?

**Comment by nicolasnoble** [comment]
I'm not sure I understand that last question. I mean, our dockerfile is still downloading rubenvb gcc at the top of it, as I didn't want to change things I wasn't sure to fully understand.

For the rest, I am more than eager to help you with migrating to mingw-w64 - with grpc I chose the path of least resistance and pounded at it until it worked for our case, but I can definitely help with refining that until it works for everyone. I remember while I was googling for these problems that I didn't seem to be entirely alone there, so we might benefit the whole community by doing this. And I would benefit from it by avoiding a custom Dockerfile in grpc :-)

I am guessing worst case scenario, we could also do something where rake-compiler-dock comes with two dockerfiles, one with the older environment for backward compatibility with gems that might have an issue with it, which would be selected by default to avoid breaking older gems, and one with the newer mingw-w64 environment, which would then be selectable using an option in the Rakefile's RakeCompilerDock.sh's command.

In all cases, let me know if this is something you're interested in, and I can start spending some time trying to make the older versions of ruby compile with mingw-w64, if that helps you.

**Comment by larskanis** [comment]
I think we mis-understood each other. Rake-compiler-dock makes use of the ancient mingw32 for ruby-1.8 and ruby-1.9 only. For ruby 2.0 to 2.3 mingw-w64 is (and was always) used in form of the rubenvb-mingw-w64-4.7.2. This matches the mingw versions that are equally used for RubyInstaller compilation.

With the installation of mingw-w64 per apt-get, you effectively disabled the rubyenvb mingw-64 version, since rubenvb is placed on the very right side of the `PATH`. So you made use of the ubuntu mingw-w64 version 4.8.2 instead of the intended rubenvb-mingw-w64 version 4.7.2. So my question is: can you build grpc with rubenvb-mingw-w64-4.7.2 instead of Ubuntu's version? That should yield to less issues.

**Comment by nicolasnoble** [comment]
I see. And I think I understand what the problem is. This isn't exactly tied to the compiler itself that is, this is tied to the runtime. I will make some more tries, but the rootcause is that if I am using an unmodified rake-compiler-dock to build grpc, then the system libraries and headers that the compiler uses are that from the mingw32 package, even though the package comes with some. Here's what I'm talking about:

```
In file included from /home/pixel/sources/grpc/include/grpc/impl/codegen/sync.h:62:0,
                 from /home/pixel/sources/grpc/include/grpc/impl/codegen/slice.h:37,
                 from /home/pixel/sources/grpc/include/grpc/impl/codegen/slice_buffer.h:37,
                 from /home/pixel/sources/grpc/include/grpc/impl/codegen/byte_buffer.h:38,
                 from /home/pixel/sources/grpc/include/grpc/byte_buffer.h:37,
                 from /home/pixel/sources/grpc/include/grpc/grpc.h:40,
                 from /home/pixel/sources/grpc/include/grpc/census.h:41,
                 from ../../../../src/ruby/ext/grpc/rb_grpc_imports.generated.h:43,
                 from ../../../../src/ruby/ext/grpc/rb_server.c:35:
/home/pixel/sources/grpc/include/grpc/impl/codegen/sync_win32.h:44:1: error: unknown type name 'CONDITION_VARIABLE'
/home/pixel/sources/grpc/include/grpc/impl/codegen/sync_win32.h:46:1: error: unknown type name 'INIT_ONCE'
```

`CONDITION_VARIABLE` is supposed to be defined in `winbase.h` or `synchapi.h`, depending on the version of the runtime, and it is defined there in your Docker environment by the package you download:

```
./opt/mingw/mingw32/i686-w64-mingw32/include/winbase.h:typedef RTL_CONDITION_VARIABLE CONDITION_VARIABLE, *PCONDITION_VARIABLE;
./opt/mingw/mingw64/x86_64-w64-mingw32/include/winbase.h:typedef RTL_CONDITION_VARIABLE CONDITION_VARIABLE, *PCONDITION_VARIABLE;
```

But the compiler isn't using it. It's using these files here:

```
./usr/i586-mingw32msvc/include/winbase.h
```

Which doesn't have the definition for that.

In the docker file from grpc, as we're installing mingw-w64 instead of mingw32, we get this:

```
./usr/i686-w64-mingw32/include/synchapi.h:  typedef RTL_CONDITION_VARIABLE CONDITION_VARIABLE, *PCONDITION_VARIABLE;
./usr/x86_64-w64-mingw32/include/synchapi.h:  typedef RTL_CONDITION_VARIABLE CONDITION_VARIABLE, *PCONDITION_VARIABLE;
./usr/share/mingw-w64/include/synchapi.h:  typedef RTL_CONDITION_VARIABLE CONDITION_VARIABLE, *PCONDITION_VARIABLE;
```

And the compiler ends up using them, and the compilation happily passes. So MAYBE it's only a matter of tweaking the compiler package you download and install in order to point at the proper system libraries.


I'll investigate a bit more on my end, to see if we can produce a happier patch and hence a pull request.

**Comment by larskanis** [comment]
Set `RUBY_CC_VERSION=2.3.0:2.2.2:2.1.6:2.0.0` and it shouldn't use the old mingw32 package.

**Comment by nicolasnoble** [comment]
And that's what we do already :-)

**Comment by metaskills** [comment]
I can say that TinyTDS does not do 1.9 gems anymore. I think 1.9 is officially unsupported too. So my vote is move along. Hope that helps.

**Comment by larskanis** [comment]
Current master branch is based on Ubuntu-16.10 and makes use of gcc-6.2.0. Old mingw32 compilers are removed, now. And target ruby versions are 2.0 to 2.4.
