### ISSUE TITLE
Cross building doesn't work for alpine3.7

### ISSUE THREAD

**Issue by TeBoring** [rake-compiler/rake-compiler-dock#20]
I used this docker to build gem for protobuf. However, when running the linux gem on alpine3.7 docker, there is segmentation fault. If I build the gem on alpine 3.7 directly, there is no segmentation fault.
For more details see https://github.com/google/protobuf/issues/4460

**Comment by larskanis** [comment]
rake-compiler doesn't recognize 2.5 as a version spec, but only 2.5.0 in RUBY_CC_VERSION. On the other hand, only the the header files of the cross ruby version are relevant, since the libruby.dll file of the cross build is replaced by the libruby.dll of the runtime ruby version, later on. That's why there's usually no need to update minor versions of the cross rubies.

Do you know whether the segfault is related to the header files? If so I'll have to find a way to update cross rubies, without breaking 3-part version specs of dependent projects.

**Comment by TeBoring** [comment]
Sorry, I don't know if it's the header file that caused the problem.
I am currently building my own docker image for 2.5.1, using similar script in https://github.com/rake-compiler/rake-compiler-dock/blob/v0.6.2/Dockerfile.
However, my image only have linux-x86 for 2.5.1, although I also mentioned x86_64 in my script. Any idea?

**Comment by TeBoring** [comment]
Changing ```parallel -j6``` to j1 fixes the problem.

**Comment by TeBoring** [comment]
The gem built by the new docker image still doesn't work.

**Comment by TeBoring** [comment]
https://github.com/docker-library/ruby/issues/196
Is this related?

**Comment by TeBoring** [comment]
I noticed that the gem we built using rake-compiler-dock is linking against glibc.
But alpine is using musl.

**Comment by larskanis** [comment]
Nokogiri is [running fine on Alpine](https://github.com/sparklemotion/nokogiri/issues/1983#issuecomment-606151999), but required a change to `sprintf()` on musl. That is beyond the scope of rake-compiler-dock, so I think rake-compiler-dock-1.0 does everything it can do to support alpine.
